language: python
python:
  - 3.6
  - 3.7
  - 3.8

dist: xenial

env:
  - BOOKMARKS_SECRET_KEY=@juyd*gto_@!uy%_z%q9=lj9l8g^w5aq-*jb#l_la9g_b3eu*g

before_install:
  - pip install -U pipenv
  - pipenv install --skip-lock
  - pipenv install codecov pytest pytest-cov --skip-lock
#install:
#  - pip install ".[test]" . # install package + test dependencies
script:
  # run tests
  - pytest --disable-pytest-warnings --cov-report term --cov=./ account/tests/

after_success:
  - codecov # submit coverage
