[development]
# General
# -----------------------------------------------------------------------------

# https://docs.djangoproject.com/en/2.2/ref/settings/#debug
DEBUG = true

# https://docs.djangoproject.com/en/2.2/ref/settings/#allowed-hosts
ALLOWED_HOSTS = ["development.com", "localhost", "0.0.0.0", "127.0.0.1"]


# Applications
# -----------------------------------------------------------------------------

# https://django-extensions.readthedocs.io/en/latest/
INSTALLED_APPS = ["django_extensions", 'dynaconf_merge']


# Databases
#------------------------------------------------------------------------------

# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
DATABASES__default__ENGINE = 'django.db.backends.sqlite3'
DATABASES__default__NAME = '@format {this.BASE_DIR}/db.sqlite3'


# Static files (CSS, JavaScript, Images)
# -----------------------------------------------------------------------------

# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATIC_URL = '/static/'


# Media files
# -----------------------------------------------------------------------------

# https://docs.djangoproject.com/en/2.2/ref/settings/#media-root
MEDIA_ROOT = '@format {this.BASE_DIR}/media'


# Email
# -----------------------------------------------------------------------------

# https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-EMAIL_BACKEND
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
